language: java

addons:
  sonarcloud:
    organization: "bqcuong"
    token:
      secure: "oaLxMHWTweAR+RgQyNnSaTtM5mRMqVdme/WoKkbsQbPhh7N0KvMXBZ9mORWuM1Rt1N/whqqH5Y3Up2l/rCjmpFOTYK3XNhSiOE/5NT00xrQ90xgKnhzOOSkJlW+BZYwf/a0bbrKOhWM42q3aj82mqgwbGwZdQcJy2xTWyYBQemjdwXWP/N8Nesmu1DBKOKbZq2PBbsIxyh6pOQN5EpORyUoSunabGL1xuORVI7zcFZpiiNEb/czTwjiVk3KsZFTDFBsoADIORQPrgG2hWAkEwzs5c+B2dXVOW5NWB6toKN1iWMGrpPTWcO75G4ZYcKWgIpUVH3MivEE5pgcB2DUf6rYkiidJWOgoYCbLFMgBCS1VaAdY+be4Qi3fHlTivaKXvWZIJ7hFxwJ5KMdmaUVW+M/fkJOw9cPjWPPUno/90R3tvtI8XvLL8z7pw+Jp1StLcXT4tM4wUgvUA8zdwzJc7omk1fDeuSS1apLFrE+apCts8UQkrIGu7GluzLm+6jt/Uqf0pPE7kHWaZZ5Rl40ObU3kjwQTG6M3PxCi1PczjWvr8UVoRnr4W/3QHihlMlneBGPMGEejd5Yo3i5ttwcnLS2Q5jtlzn7pSsvi0+JbCK+Zwi1O1fNsXDJ06UyXEBqeQxvs6phLRYZNVi+emv8rxnzuhR42CMTKAwKlDXdWHr0="

install: true

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=bqcuong_Juliet-Test-Suite
